### ISSUE TITLE
Feature request: remove @typedef when includeTypes is set to false

### ISSUE THREAD

**Issue by Glitch752** [Nyphet/jsdoc-generator#12]
Thank you for this extension!  The only issue I've had with it is, after setting includeTypes to false, @typedef is still included in the JSDocs generated.

It would be great to have either:
- When includeTypes is false, no @typedef is generated
- A setting to remove arbitrary tags

If you would like, I can create a pull request for this. Thanks!

**Comment by Nyphet** [comment]
Makes sense, I'll go with removing the @typedef tag.  
Don't worry, no need to create a PR, it should be as simple as adding an if statement!

**Comment by Nyphet** [comment]
This fix will come with version 2.0.0
