### ISSUE TITLE
Alignment options

### ISSUE THREAD

**Issue by Tain101** [Nyphet/jsdoc-generator#16]
**Is your feature request related to a problem? Please describe.**
I like to vertically align my code when I can, having this bet a setting or supported feature would be a nice convenience for me.

**Describe the solution you'd like**
this documentation:
```js
/**
 * Description placeholder
 * @date 9/30/2023
 *
 * @param {*} paramOne param description
 * @param {*} ptwo param description
 * @param {*} parameterThree param description
 * @param {...{}} args param description
 * 
 * @returns {boolean} return description
 */
 ```
 would be aligned like this
 ```js
 /**
 * Description placeholder
 * @date 9/30/2023
 *
 * @param {*}      paramOne        param description
 * @param {*}      ptwo            param description
 * @param {*}      parameterThree  param description
 * @param {...{}}  args            param description
 * 
 * @returns {boolean}              return description
 */
 ```

**Describe alternatives you've considered**
Either as a true/false option, or as some sort of format support for tags, similar to the [Doxygen Document Generator](https://github.com/cschlosser/doxdocgen/blob/master/CHANGELOG.md#alignment) extension.

**Comment by Nyphet** [comment]
This feature will be available with version v2.0.0, but it may take a while to publish it since Google Makersuite is taking it's sweet time to grant me access and I need it to develop another feature.  
Anyway, when version v2.0.0 will be released, feel free to comment here again if something's wrong.
