### ISSUE TITLE
Multiline params are not recognized with typescript syntax highlighting

### ISSUE THREAD

**Issue by Kas-tle** [Nyphet/jsdoc-generator#18]
**Describe the bug**
Multiline params are not recognized with typescript syntax highlighting

**To Reproduce**
1. Create a function with an argument that containers a type defined over multiple lines
2. Auto-generate JSDoc comments for the file
3. Observe that the syntax highlighting does not work because no asterisks were inserted on new lines

**Expected behavior**
An asterisk is inserted at each new line so the syntax highlighting works correctly

**Screenshots**
Actual output:
![image](https://github.com/Nyphet/jsdoc-generator/assets/26531652/fa26a976-e3aa-44fa-9613-6323078f243e)

Expected output:
![image](https://github.com/Nyphet/jsdoc-generator/assets/26531652/45b25959-0e4b-403f-815d-a8e5e744b866)

**Additional context**
See https://github.com/microsoft/vscode/issues/108237

**Environment used**
Typescript version: 5.2.2
VSC version: 1.84.0-insider
OS: Windows 11

**Comment by Nyphet** [comment]
Fixed in [v2.0.1](https://github.com/Nyphet/jsdoc-generator/releases/tag/v2.0.1).
