### ISSUE TITLE
Unable to generate JSDoc: typescriptreact is not supported.

### ISSUE THREAD

**Issue by cabanossi** [Nyphet/jsdoc-generator#2]
Hello!
I use Typescript with React.
The file extentions is .tsx
The association for .tsx ist "TypeScript React".

If i want "Generate JSDoc" i become the Error:
Unable to generate JSDoc: typescriptreact is not supported.

Can you fix this?

**Comment by Nyphet** [comment]
Hi!
This should be fixed with the new [1.1.0 Release](https://github.com/Nyphet/jsdoc-generator/releases/tag/v1.1.0).
This new release should automatically be available on VSC next time you open it.
Let me know if the problem persists or if there's any other problem, I'm closing this for now.
