### ISSUE TITLE
[Feature request]Add extension settings to exclude @export and @async

### ISSUE THREAD

**Issue by smallStall** [Nyphet/jsdoc-generator#3]
**Is your feature request related to a problem? Please describe.**
When JSDoc is generated from a function, @exprot and @async are added.
I don't need @export and @async because I checked by the types instead of them.

**Describe the solution you'd like**
Add extension settings to exclude @export and @async

**Environment used**
Typescript version:4.5.5 
VSC versione: 1.66.1
OS: Windows 11

**Comment by Nyphet** [comment]
I added two new settings, one to include/exclude the export tag and one to include/exclude the async tag.  
They both default to true, so be sure to change them in the settings according to your needs.  
The update should be already available on VSC, let me know if there is any problem. Closing the issue.
