### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by teshtek** [Nyphet/jsdoc-generator#5]
**Describe the bug**
The messages says: Correctly generated 19 JSDocs! but just on the last function was generated the comment

**To Reproduce**
1. Generate for current file

**Expected behavior**
When try to generate comments for a file, it says it did 19 docs but just on last function the comment was added 

**Environment used**
Typescript version: 4.9.5
VSC versione:  1.75.1
OS: Darwin x64 22.1.0

**Comment by Nyphet** [comment]
Can you please provide a sample video so that I can better understand and replicate the issue?

**Comment by Nyphet** [comment]
Could replicate the issue, working on it.

**Comment by Nyphet** [comment]
Fixed with version v1.2.0
