### ISSUE TITLE
What about generic extends in Typescript

### ISSUE THREAD

**Issue by MasedMSD** [Nyphet/jsdoc-generator#8]
The code:
```ts
const sayHello = <N extends string>(name: N): `Hello, ${N}` => {
	return `Hello, ${name}`;
};
```
Generating:
```ts
/**
 * Description placeholder
 *
 * @template N
 * @param {N} name
 * @returns {`Hello, ${N}`}
 */
```
But should be
```ts
/**
 * Description placeholder
 *
 * @template {string} N <-- extends string
 * @param {N} name
 * @returns {`Hello, ${N}`}
 */
```

**Comment by Nyphet** [comment]
I should also add support for default values for type parameters.  
I'm attaching here a link to the official JSDoc documentation so that when I start working on this I have the reference guide: https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html#template

**Comment by Nyphet** [comment]
Keep an eye on the v2.0.0 release because it's the one that will have the fix for this issue!
